apiVersion: v1
kind: Service
metadata:
  name: simple-01-lb-service
spec:
  type: LoadBalancer # ClusterIp, # NodePort
  selector:
    app: simple-01
  ports:
    - name: http
      port: 80 # Service Port
      targetPort: 8080 # Container Port
