apiVersion: v1
kind: Service
metadata:
  name: todoapp-lb-service
spec: 
  type: LoadBalancer
  selector: 
    app: todoapp
  ports: 
    - port: 80 # Service Port
      targetPort: 8080 # Container Port
