apiVersion: v1
kind: ConfigMap
metadata:
  name: todoapp-dbcreation-script
data: 
  mysql_todoapp.sql: |-
    USE todos_db;
    
    CREATE TABLE IF NOT EXISTS todos (
        id INT AUTO_INCREMENT PRIMARY KEY,
        title VARCHAR(255) NOT NULL,
        completed BOOLEAN DEFAULT FALSE
    );
